# This profile uses the docker-compose DNS names and is activated for the default docker-compose build

spring:
  rabbitmq:
    host: mls-amqp
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
application:
  geocoder:
    priority: 2
    requeue: true
logging:
  config: /config/log-docker.xml
  level:
    root: info
    at.wrk.fmd.mls: debug
